catalog/urls.py
# coding=utf-8
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', views.product, name='product'),

]

djangoecommerce/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from core import views
from catalog import views as views_catalog


urlpatterns = [
    url(r'^$', views.index,name= 'index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
# coding=utf-8
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador',max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified =  models.DateTimeField('Modificado em', auto_now=True)


    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('catalog:category', kwargs={'slug':self.slug})



class Product(models.Model):
    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador',max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='Categoria')
    description = models.TextField('Descrição', blank=True)

    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified =  models.DateTimeField('Modificado em', auto_now=True)


    class Meta:

        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']


    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('catalog:product', kwargs={'slug':self.slug})

core/models.py
from django.db import models

# Create your models here.

core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='Email')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())





    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome:{0}\nEmail:{1}\n{2}'.format(name,email,message)
        send_mail('Contato do Django E-Commerce', message, settings.DEFAULT_FROM_EMAIL,
        [settings.DEFAULT_FROM_EMAIL]

        )

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Product, Category

#usando CBV

class ProductListView(generic.ListView):

    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 3

product_list = ProductListView.as_view()



'''
view com funçoes

def product_list(request):
    context = {
        'product_list': Product.objects.all()
    }
    return render(request, 'catalog/product_list.html', context)
'''


class CategoryListView(generic.ListView):

    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 3

#Obter a lista de itens para esta view. Este deve ser um iterable e pode ser um queryset
# (em que o comportamento específico do queryset será ativado).
#queryset , é uma lista de objetos de um dado modelo.
    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

#Retorna dados de contexto para exibir a lista de objetos.
    def get_context_data(self, **kwargs):

        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()





'''

def category(request, slug):
    category = Category.objects.get(slug=slug)
    context = {
        'current_category': category,
        'product_list': Product.objects.filter(category=category),

    }

    return render(request, 'catalog/category.html',context)

'''







def product(request, slug):
    product = Product.objects.get(slug=slug)

    context = {
        'product':product

    }
    return render(request, 'catalog/product.html',context)

core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import View, TemplateView
from .forms import ContactForm



class IndexView(TemplateView):

    template_name = 'index.html'


index = IndexView.as_view()



#Essa view foi criada na app core pq é generica.

def contact(request):
    success = True
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.send_mail()
            success = True
    else:
        form = ContactForm()
    context = {
        'form' : form,
        'success': success
    }

    return render(request, 'contact.html', context)

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
{{ current_category }}|{{block.super}}
{% endblock %}

{% block container %}

<div class="page-header">
  <h1>{{ current_category }}</h1>
</div>
<div class="row">
  {% for product in product_list %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <a href="{{ product.get_absolut_url }}">
        <img src="http://placehold.it/350x250" alt="" />
      </a>
      <div class="caption">
        <h3>{{product}}</h3>
        {{ product.description|linebreaks}}
        <p><a href="{{ product.get_absolut_url }}" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% pagination request paginator page_obj%}

{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}


{% block title %}
{{product}}|{{block.super}}
{% endblock %}


{% block container %}

<div class="page-header">
  <h1>{{product}}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <a href="#" class="thumbnail">
      <img src="http://placehold.it/350x250" alt="" />
    </a>
  </div>
  <div class="col-sm-8">
    {{product.description|linebreaks}}
  </div>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}


 {% load pagination %}

{% block title %}
Listagem de Produtos|{{block.super}}
{% endblock %}

{% block container %}

<div class="page-header">
  <h1>Produtos</h1>
</div>
<div class="row">
  {% for product in products %}
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <a href="{{ product.get_absolut_url }}">
        <img src="http://placehold.it/350x250" alt="" />
      </a>
      <div class="caption">
        <h3>{{product}}</h3>
        {{ product.description|linebreaks}}
        <p><a href="{{ product.get_absolut_url }}" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% pagination request paginator page_obj%}

{% endblock %}

core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %} </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css'%}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">

									{% for category in categories %}
										<li><a href="{{category.get_absolut_url}}">{{ category }}</a></li>
									{% endfor %}

              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Minha Conta</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">

	    {% block container %}{% endblock %}

		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js'%}"></script>
</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
Contato|{{block.super}}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
      Mensagem enviada com sucesso

    </div>
    {% endif %}

  <form class="form-horizontal" action="" method="post">
    {% csrf_token %}

    <fieldset>
      {% for field in form %}

        <div class="form-group" {% if field.errors %} has-error{% endif %}>
          <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
          <div class="col-md-9">
            {% render_field field class='form-control' %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {%endfor%}
          </div>
        </div>
        {% endfor %}
      <div class="form-group">
          <div class="col-md-9 col-md-offset-3">
            <button type="submit" class="btn btn-primary">Enviar</button>
          </div>
        </div>
    </fieldset>
  </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="container">
<div class="jumbotron page-header">
	<h1>Django E-Commerce</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
	<p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

core/templates/pagination.html
<div class="row">
  <div class="col-md-12">
       <nav>
           <ul class="pagination">
              {% for page in paginator.page_range  %}
                <li{% if page_obj.number == page%} class="active"{% endif%}><a href="?page={{page}}{{getvars}}">{{page}}</a></li>
               {% endfor %}
           </ul>
      </nav>
  </div>
</div>